bug fixes and extensions for correct startup

diff --git a/client/wg-sixbroker b/client/wg-sixbroker
--- a/client/wg-sixbroker
+++ b/client/wg-sixbroker
@@ -12,9 +12,9 @@ SERVER=${CONFIG//\.*/}
 CONFIG=${WGDIR}/${SERVER}.conf
 HN=$(hostname)
 
-SK=$(cat ${WGDIR}/servers/${SERVER}.publickey)
-HK=$(cat ${WGDIR}/private/${HN}.publickey)
-PK=$(cat ${WGDIR}/private/${HN}.privatekey)
+SK=$(cat ${WGDIR}/servers/${SERVER}.publickey 2>/dev/null)
+HK=$(cat ${WGDIR}/private/${HN}.publickey 2>/dev/null)
+PK=$(cat ${WGDIR}/private/${HN}.privatekey 2>/dev/null)
 
 check_keys() {
         if [ -z "${SK}" ]
@@ -33,7 +33,11 @@ check_keys() {
         then
 		sed -i "s|PrivateKey.*|PrivateKey = ${PK}|g" ${CONFIG}
 	fi
-       
+	if [ -z "${HK}" ]
+	then
+		echo "Can't continue - client publickey is missing!"
+		exit 1
+	fi
 }
 
 stop() {
@@ -49,8 +53,11 @@ start() {
 
 	DEV=$(awk 'BEGIN { IGNORECASE=1 } /^[a-z0-9]+[ \t]+00000000/ { print $1 }' /proc/net/route)
 	DGW=$(ip route show dev ${DEV} | grep default | awk '{print $3}')
-	sed -i "s/\(ip -4 route add .*\) via .*/\1 via ${DGW}/g" ${CONFIG}
+	PEER=$(grep '^Endpoint' ${CONFIG} | sed 's/.*= \(.*\):.*/\1/g;')
+	sed -i "s/\(ip -4 route add\) \(.*\) via .*/\1 ${PEER} via ${DGW}/g" ${CONFIG}
+	sed -i "s/\(ip -4 route del\) \(.*\) via .*/\1 ${PEER} via ${DGW}/g" ${CONFIG}
 	sed -i "s/default dev.*/default dev ${SERVER}/g" ${CONFIG}
+	sed -i "s/default via.*/default via ${DGW}/g" ${CONFIG}
 
 	wg-quick up ${SERVER}
 
@@ -78,14 +85,14 @@ status() {
 CPORT=$(grep -i 'ListenPort' ${CONFIG} | cut -f 2 -d=)
 
 case ${1} in
-	start) start
+	start) check_keys; start
 		;;
 	stop) stop
 		;;
 	keys) check_keys;
 		grep Key ${CONFIG}
 		;;
-	status) status
+	status) check_keys; status
 		;;
 	*) echo "$0 start|stop|status"
 		;;
